### ISSUE TITLE
reverse proxy document and recommendations

### ISSUE THREAD

**Issue by clach04** [Tanq16/local-content-share#9]
This looks awesome! Do you have any experience using this with a reverse proxy (and PWA)?

If I get some spare time I may give this a go with Caddy using the technique described in https://github.com/clach04/best_python_dockerfile_ever/blob/master/docker-compose_caddy.yml

**Comment by Tanq16** [comment]
Hello! Thank you!

Yes, I and a couple of my friends use it with Nginx Proxy Manager as the rev. proxy locally and Cloudflare tunnels externally. It works as expected. I don't have personal experience tinkering with Caddy, but I don't foresee any particular issues in that setup.

For reference, my stack yaml is as follows:

```yaml
version: "3.8"
services:
  local-content-share:
    image: tanq16/local-content-share:main
    container_name: local-content-share
    volumes:
      - $HOME/localcontentshare:/app/data
    networks:
      - proxy-net
networks:
  proxy-net:
    external: true
```

Here, `proxy-net` is the Docker network that contains all my services, so I don't expose any ports on the machine and Nginx Proxy Manager is able to point to it via service name (`local-content-share`).
